swagger: "2.0"
info:
  version: "1.0.0"
  title: "Library API"
  description: "API для управления библиотекой"
host: "localhost:8080"
basePath: "/swagger"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths: {}
definitions: {}
